runs:
  using: 'composite'
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v5
      with:
        node-version: 24

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: true
