name: ci

on: push

jobs:
  lint-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-env
      - run: pnpm run lint

  lint-renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-env
      - run: npx --package renovate -c renovate-config-validator

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-env
      - run: pnpm run build
