name: deploy

on:
  workflow_dispatch:
    inputs:
      prod_env:
        description: 'Production'
        required: false
        default: true
        type: boolean
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'deploy'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: set deploy prod flag
        id: set_vercel_args
        run: |
          if [ "$PROD_ENV" == 'true' ]
          then
              echo "::set-output name=args::--prod"
          else
              echo "::set-output name=args::"
          fi
        env:
          PROD_ENV: ${{ inputs.prod_env }}
      - uses: amondnet/vercel-action@v25
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: ${{ steps.set_vercel_args.outputs.args }}
          working-directory: dist
